"""Generate the CPU-side notebooks (01, 02, 04).

Generated rather than hand-written so they stay in sync with src/. Re-run after
changing config and commit the result. The Colab training notebook has its own
generator, _build_colab_nb.py.
"""
import json, pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))
from src import config

# Tiny constructors so the notebook bodies below stay readable as prose.
def md(*l): return {"cell_type": "markdown", "metadata": {}, "source": "\n".join(l)}
def code(*l): return {"cell_type": "code", "metadata": {}, "execution_count": None,
                      "outputs": [], "source": "\n".join(l)}
def nb(cells):
    return {"cells": cells, "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"}},
        "nbformat": 4, "nbformat_minor": 5}

HERE = pathlib.Path(__file__).parent
BOOT = ("import sys, pathlib",
        "sys.path.insert(0, str(pathlib.Path.cwd().parent))  # import src/ from notebooks/",
        "import numpy as np, pandas as pd, matplotlib.pyplot as plt")

# ---------------------------------------------------------------- 01
n01 = nb([
md("# 01 — Data exploration",
   "",
   "What the raw price series looks like before any of it becomes a picture. The goal here",
   "is to know the shape of the data well enough that later results are interpretable: how",
   "many bars there are, how the up/down split sits, and how much of the target is simply",
   "the long upward drift of an index."),
code(*BOOT,
     "from src import config",
     "from src.data_pipeline.fetch_ohlc import fetch_ohlc",
     "",
     "bars = fetch_ohlc(config.TICKER)",
     "print(f'{len(bars)} bars  {bars.index[0].date()} -> {bars.index[-1].date()}')",
     "bars.tail()"),
md("## Price history and the three chronological splits",
   "",
   "Splits are by date, never random, and the shaded gaps are the embargo: windows there are",
   "discarded because they would otherwise straddle a boundary and share candles across splits."),
code("fig, ax = plt.subplots(figsize=(13, 4.5))",
     "ax.semilogy(bars.index, bars['Close'], lw=0.8, color='#222')",
     "for date, label, colour in [(config.TRAIN_END, 'train ends', '#2E7D32'),",
     "                            (config.VAL_END, 'val ends', '#EF6C00')]:",
     "    ax.axvline(pd.Timestamp(date), color=colour, ls='--', lw=1.4, label=label)",
     "ax.set_title(f'{config.TICKER} close (log scale) and split boundaries')",
     "ax.set_ylabel('close'); ax.legend(); ax.grid(alpha=0.2)",
     "plt.tight_layout(); plt.show()"),
md("## How much of the target is just drift?",
   "",
   "The share of up-days is the accuracy a model gets by always predicting \"up\". Every",
   "later accuracy number has to be read against this, not against 50%."),
code("from src.downstream_signal.labels import base_rate, next_day_direction",
     "",
     "y = next_day_direction(bars)",
     "print(f'up-days overall: {base_rate(y):.4f}')",
     "for name, mask in [('train', y.index <= config.TRAIN_END),",
     "                   ('val', (y.index > config.TRAIN_END) & (y.index <= config.VAL_END)),",
     "                   ('test', y.index > config.VAL_END)]:",
     "    print(f'  {name:<6} n={mask.sum():>5}  up-rate={y[mask].mean():.4f}')"),
md("## Daily return distribution",
   "",
   "Fat tails and volatility clustering are why volatility features are in the baseline at all."),
code("rets = np.log(bars['Close']).diff().dropna()",
     "fig, axes = plt.subplots(1, 2, figsize=(13, 4))",
     "axes[0].hist(rets, bins=140, color='#3949AB', alpha=0.85)",
     "axes[0].set_yscale('log'); axes[0].set_title('daily log returns (log-count)')",
     "axes[1].plot(rets.index, rets.rolling(20).std() * np.sqrt(252), lw=0.7, color='#C62828')",
     "axes[1].set_title('20-day realised volatility, annualised'); axes[1].grid(alpha=0.2)",
     "plt.tight_layout(); plt.show()",
     "print(rets.describe())"),
md("## One rendered chart",
   "",
   "This is literally all the detector ever sees: 20 candles, no axes, no gridlines, no volume."),
code("from src.data_pipeline.render_charts import render_window",
     "",
     "window = bars.iloc[-config.WINDOW:]",
     "image, mapper = render_window(window)",
     "plt.figure(figsize=(6, 6)); plt.imshow(image); plt.axis('off')",
     "plt.title(f'{config.TICKER} to {window.index[-1].date()}'); plt.show()",
     "print('image', image.shape)"),
])

# ---------------------------------------------------------------- 02
n02 = nb([
md("# 02 — Labelling development",
   "",
   "How rule-based labels become bounding boxes, and how often each pattern actually occurs.",
   "",
   "**The thing to keep in mind throughout:** these labels are TA-Lib's opinion, not a human's.",
   "This notebook is where that becomes concrete — you can look at a box and judge for yourself",
   "whether you would have called it the same pattern."),
code(*BOOT,
     "from src import config",
     "from src.data_pipeline.fetch_ohlc import fetch_ohlc",
     "from src.labeling.talib_labeler import label_patterns, pattern_counts",
     "",
     "bars = fetch_ohlc(config.TICKER)",
     "labels = label_patterns(bars)",
     "print(f'{len(labels)} pattern instances over {len(bars)} bars')",
     "labels.head(10)"),
md("## Class balance is severe, and it is not a bug",
   "",
   "Doji fires an order of magnitude more often than the three-candle patterns. This is a",
   "property of the rules, not of the sampling, and it is why detection results are reported",
   "per class instead of as one averaged mAP."),
code("counts = pattern_counts(labels)",
     "fig, ax = plt.subplots(figsize=(9, 4))",
     "colours = ['#2E7D32' if config.PATTERN_DIRECTION[c] > 0 else",
     "           '#C62828' if config.PATTERN_DIRECTION[c] < 0 else '#757575'",
     "           for c in counts.index]",
     "ax.bar(counts.index, counts.values, color=colours)",
     "ax.set_yscale('log'); ax.set_ylabel('instances (log)')",
     "ax.set_title(f'{config.TICKER}: pattern frequency, whole history')",
     "plt.xticks(rotation=35, ha='right'); plt.tight_layout(); plt.show()",
     "print(counts.to_string())"),
md("## Why SPY alone is not enough",
   "",
   "In the training period the two three-candle classes fall below the minimum-instance floor.",
   "That is the reason auxiliary tickers exist — dropping two of eight classes was the",
   "alternative."),
code("train_hits = labels[labels.date <= config.TRAIN_END]",
     "tc = train_hits.pattern.value_counts().reindex(config.CLASSES, fill_value=0)",
     "for c in config.CLASSES:",
     "    flag = '  <-- below the floor' if tc[c] < config.MIN_INSTANCES_PER_CLASS else ''",
     "    print(f'{c:<20}{tc[c]:>6}{flag}')",
     "print(f'\\nfloor = {config.MIN_INSTANCES_PER_CLASS} instances')"),
md("## From a rule hit to a box on a picture",
   "",
   "A multi-bar pattern is reported by TA-Lib on the bar where it *completes*, so a three-bar",
   "Morning Star flagged at index i occupies bars i-2..i. The box spans all of them. Geometry",
   "comes from the rendered figure's own transform, so it is exact rather than estimated."),
code("from src.data_pipeline.render_charts import render_window",
     "from src.labeling.bbox_utils import pattern_bbox",
     "from src.labeling.build_dataset import _labels_in_window",
     "",
     "by_pos = {}",
     "for rec in labels.to_dict('records'): by_pos.setdefault(rec['position'], []).append(rec)",
     "",
     "def show(end_pos):",
     "    \"\"\"Render the window ending at end_pos with every in-frame pattern boxed.\"\"\"",
     "    start = end_pos - config.WINDOW + 1",
     "    win = bars.iloc[start:end_pos + 1]",
     "    img, mapper = render_window(win)",
     "    fig, ax = plt.subplots(figsize=(7.5, 7.5)); ax.imshow(img); ax.axis('off')",
     "    for hit in _labels_in_window(by_pos, end_pos, config.WINDOW):",
     "        last_c = hit['position'] - start; first_c = last_c - hit['span'] + 1",
     "        seg = bars.iloc[start + first_c: start + last_c + 1]",
     "        cx, cy, w, h = pattern_bbox(mapper, float(seg['High'].max()),",
     "                                    float(seg['Low'].min()), first_c, last_c)",
     "        x, y = (cx - w/2) * img.shape[1], (cy - h/2) * img.shape[0]",
     "        colour = ('#2E7D32' if config.PATTERN_DIRECTION[hit['pattern']] > 0 else",
     "                  '#C62828' if config.PATTERN_DIRECTION[hit['pattern']] < 0 else '#455A64')",
     "        ax.add_patch(plt.Rectangle((x, y), w*img.shape[1], h*img.shape[0],",
     "                                   fill=False, edgecolor=colour, lw=2))",
     "        ax.text(x, y - 4, hit['pattern'], color=colour, fontsize=8, weight='bold')",
     "    ax.set_title(f\"{config.TICKER} window ending {win.index[-1].date()}\")",
     "    plt.tight_layout(); plt.show()",
     "",
     "show(len(bars) - 1)"),
md("## A rare three-candle pattern",
   "",
   "Find a Morning Star and look at it. Does the rule's call match what you would have marked?",
   "That question is the whole limitation of weak labels, in one picture."),
code("ms = labels[labels.pattern == 'MorningStar']",
     "print(f'{len(ms)} Morning Stars; showing the most recent')",
     "if len(ms):",
     "    show(int(ms.position.iloc[-1]))"),
md("## Do patterns cluster in time?",
   "",
   "If hits bunched into a few regimes, the chronological splits could hand one split most of",
   "a class. Worth checking before trusting per-class test numbers."),
code("per_year = labels.groupby([labels.date.dt.year, 'pattern']).size().unstack(fill_value=0)",
     "fig, ax = plt.subplots(figsize=(13, 4.5))",
     "per_year.plot(kind='area', stacked=True, ax=ax, lw=0, alpha=0.85, colormap='tab10')",
     "ax.set_title('pattern hits per year'); ax.set_xlabel('year'); ax.grid(alpha=0.2)",
     "ax.legend(fontsize=7, ncol=4); plt.tight_layout(); plt.show()"),
])

# ---------------------------------------------------------------- 04
n04 = nb([
md("# 04 — Downstream signal evaluation",
   "",
   "The question the project exists to answer: **does knowing the detector saw a pattern help",
   "predict the next day's direction?**",
   "",
   "Requires trained weights on the Hugging Face model repo (notebook 03) and the rendered",
   "signal set (`python -m src.labeling.build_dataset`).",
   "",
   "Whatever this shows is what gets published. A null result is the honest and more",
   "interesting outcome, and the report generator words itself accordingly."),
code(*BOOT,
     "from src import config",
     "from src.data_pipeline.fetch_ohlc import fetch_ohlc",
     "from src.downstream_signal.features import build_features",
     "from src.downstream_signal.labels import next_day_direction, next_day_return",
     "from src.downstream_signal.run_study import build_pattern_features",
     "from src.downstream_signal.model import assemble_matrix",
     "",
     "bars = fetch_ohlc(config.TICKER)",
     "baseline = build_features(bars)",
     "target = next_day_direction(bars)",
     "fwd = next_day_return(bars)",
     "pattern = build_pattern_features()   # cached after the first (slow) run",
     "X, y = assemble_matrix(baseline, pattern, target)",
     "print(f'{len(X)} rows x {X.shape[1]} features, {X.index.min().date()} -> {X.index.max().date()}')"),
md("## How often does the detector actually fire?",
   "",
   "Check this before interpreting any null result. If the pattern columns were almost always",
   "zero, \"patterns do not help\" would just mean \"nothing was detected\" — a different and much",
   "less interesting finding."),
code("from src.detection.infer import PATTERN_FEATURES",
     "",
     "share = (pattern.loc[X.index, 'det_any'] > 0).mean()",
     "print(f'days with a detection on the latest candle: {share:.1%}')",
     "print(f'mean detections per chart: {pattern.loc[X.index, \"det_count\"].mean():.2f}\\n')",
     "fired = (pattern.loc[X.index, [f'det_{c}' for c in config.CLASSES]] > 0).mean()",
     "fired.index = config.CLASSES",
     "fig, ax = plt.subplots(figsize=(9, 3.6))",
     "ax.bar(fired.index, fired.values, color='#3949AB')",
     "ax.set_ylabel('share of days'); ax.set_title('detection rate on the latest candle')",
     "plt.xticks(rotation=35, ha='right'); plt.tight_layout(); plt.show()"),
md("## Univariate check, before any model",
   "",
   "For each class: the next-day up-rate on days the detector fired, against the overall rate.",
   "Wilson intervals, because some classes fire on only a handful of days and a bare percentage",
   "would be badly misleading."),
code("def wilson(k, n, z=1.96):",
     "    \"\"\"Wilson score interval; behaves sensibly for tiny n, unlike the normal approx.\"\"\"",
     "    if n == 0: return (np.nan, np.nan)",
     "    p = k / n; d = 1 + z**2/n",
     "    c = (p + z**2/(2*n)) / d",
     "    hw = z * np.sqrt(p*(1-p)/n + z**2/(4*n**2)) / d",
     "    return c - hw, c + hw",
     "",
     "rows = []",
     "overall = y.mean()",
     "for c in config.CLASSES:",
     "    mask = pattern.loc[X.index, f'det_{c}'] > 0",
     "    n = int(mask.sum())",
     "    if n == 0:",
     "        rows.append({'pattern': c, 'days': 0}); continue",
     "    k = int(y[mask].sum()); lo, hi = wilson(k, n)",
     "    rows.append({'pattern': c, 'days': n, 'up_rate': k/n,",
     "                 'ci_low': lo, 'ci_high': hi,",
     "                 'vs_overall': k/n - overall,",
     "                 'distinguishable': not (lo <= overall <= hi)})",
     "uni = pd.DataFrame(rows)",
     "print(f'overall up-rate: {overall:.4f}')",
     "uni"),
md("## The walk-forward comparison",
   "",
   "Expanding window, refit every January, never shuffled. Both variants are scored on exactly",
   "the same days so the comparison is paired."),
code("from src.downstream_signal.backtest import run_comparison",
     "",
     "report = run_comparison(X, y, fwd,",
     "                        out_path=config.RESULTS_DIR / 'downstream_signal_comparison.json')",
     "b, p = report['variants']['baseline'], report['variants']['with_patterns']",
     "pd.DataFrame({'baseline': b, 'with_patterns': p}).loc[",
     "    ['accuracy', 'base_rate', 'roc_auc', 'f1', 'brier',",
     "     'strategy_return_net', 'buy_hold_return', 'sharpe_net', 'n_trades']]"),
md("## Is the difference real, or is it noise?",
   "",
   "Two accuracies differing by a few tenths of a percent over ~1,700 days are not",
   "distinguishable by eye. McNemar's test uses only the days where the two models disagreed;",
   "the paired bootstrap gives an interval for the difference itself."),
code("bs, mc = report['comparison']['bootstrap'], report['comparison']['mcnemar']",
     "print(f\"accuracy difference  {bs['delta_accuracy']:+.4f}\")",
     "print(f\"95% bootstrap CI     {bs['ci95_low']:+.4f} to {bs['ci95_high']:+.4f}\")",
     "print(f\"P(difference > 0)    {bs['prob_delta_positive']:.3f}\")",
     "print(f\"McNemar p-value      {mc['p_value']:.4f}  \"",
     "      f\"({mc['discordant_pairs']} discordant days)\")",
     "",
     "crosses_zero = bs['ci95_low'] <= 0 <= bs['ci95_high']",
     "print('\\nVERDICT:', 'NO measurable improvement — the interval contains zero.'",
     "      if crosses_zero or mc['p_value'] >= 0.05 else",
     "      'A statistically detectable difference. Judge the effect SIZE, not just the p-value.')"),
md("## Write the results into the README"),
code("from src.evaluation.report import inject, build_report",
     "print(build_report())",
     "inject()"),
])

for name, doc in [("01_data_exploration.ipynb", n01),
                  ("02_labeling_dev.ipynb", n02),
                  ("04_downstream_signal_eval.ipynb", n04)]:
    (HERE / name).write_text(json.dumps(doc, indent=1))
    print("wrote", name, f"({len(doc['cells'])} cells)")
