"""Package and publish the dataset, weights and demo Space to Hugging Face.

The dataset is uploaded as one gzipped tarball per split rather than as ~25,000
loose files.  The Hub copes with either, but a tarball makes the Colab download
a single fast request instead of thousands, and it keeps the split structure
atomic: you cannot end up with images from one split and labels from another.

Credentials come from ``HF_TOKEN`` in the environment or ``.env``.  No token is
ever written to a file, printed, or committed.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import tarfile
from pathlib import Path

from src import config

logger = logging.getLogger(__name__)

SPLITS = ("train", "val", "test")


def _token() -> str:
    """Read HF_TOKEN from the environment, loading .env first if present."""
    from dotenv import load_dotenv

    load_dotenv(config.PROJECT_ROOT / ".env")
    token = os.environ.get("HF_TOKEN", "").strip()
    if not token:
        raise RuntimeError(
            "HF_TOKEN is not set. Create .env from .env.example and fill it in."
        )
    return token


def pack_split(split: str, out_dir: Path) -> Path:
    """Tar+gzip one split's images and labels into ``out_dir/<split>.tar.gz``.

    Paths inside the archive are relative (``images/<split>/...``,
    ``labels/<split>/...``) so extracting all three into one directory
    reconstructs the Ultralytics layout exactly.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    archive = out_dir / f"{split}.tar.gz"
    with tarfile.open(archive, "w:gz") as tf:
        for kind, root in (("images", config.IMAGES_DIR), ("labels", config.LABELS_DIR)):
            src = root / split
            if src.exists():
                tf.add(src, arcname=f"{kind}/{split}")
    logger.info("packed %s -> %s (%.1f MB)", split, archive,
                archive.stat().st_size / 1e6)
    return archive


def dataset_card(stats: dict | None) -> str:
    """Compose the dataset README, including the class balance table."""
    rows = ""
    if stats:
        rows = "\n".join(
            f"| {c} | " + " | ".join(
                str(stats.get(s, {}).get("instances", {}).get(c, 0)) for s in SPLITS
            ) + " |"
            for c in config.CLASSES
        )
        totals = "| **images** | " + " | ".join(
            str(stats.get(s, {}).get("images", 0)) for s in SPLITS
        ) + " |"
        rows = f"{rows}\n{totals}"

    return f"""---
license: mit
task_categories: [object-detection]
tags: [candlestick, finance, yolo, technical-analysis]
---

# Candlestick pattern detection dataset

640x640 renderings of 20-candle daily OHLC windows, with YOLO-format boxes for
{config.NUM_CLASSES} candlestick patterns.

## Labels are rule-based, not human-verified

Every box was generated by TA-Lib's `CDLxxx` functions. Nobody annotated these
charts by hand. A model trained here learns to imitate TA-Lib's published
heuristic, which does not always agree with what a discretionary trader would
mark on the same chart. Treat the labels as a reproducible rule, not as truth.

## Splits are chronological, with an embargo

| split | period |
|---|---|
| train | through {config.TRAIN_END} |
| val | {config.TRAIN_END} to {config.VAL_END} |
| test | after {config.VAL_END} |

Consecutive windows overlap in 19 of 20 candles, so the first
{config.EMBARGO_BARS} windows after each boundary are discarded. Val and test
images therefore share no candle with any training image. Splits are never
random.

## Contents

| class | {" | ".join(SPLITS)} |
|---|---|---|---|
{rows}

`train` also contains auxiliary large-cap tickers
({", ".join(config.DETECTION_EXTRA_TICKERS)}), included solely to give the rare
three-candle patterns enough examples. `val` and `test` are
{config.TICKER}-only, so held-out metrics describe the instrument the downstream
study actually uses.

## Layout

```
images/{{train,val,test}}/TICKER_YYYYMMDD.png
labels/{{train,val,test}}/TICKER_YYYYMMDD.txt
```

A filename's date is the window's **last** candle: the chart contains bars up to
and including that date and nothing after it.

Code: https://github.com/{config.HF_USER}/{config.GITHUB_REPO}
"""


def ensure_repos(token: str | None = None) -> None:
    """Create the model, dataset and Space repos if they do not exist yet."""
    from huggingface_hub import HfApi

    token = token or _token()
    api = HfApi(token=token)
    for repo_id, kind, extra in (
        (config.HF_MODEL_REPO, "model", {}),
        (config.HF_DATASET_REPO, "dataset", {}),
        (config.HF_SPACE_REPO, "space", {"space_sdk": "gradio"}),
    ):
        api.create_repo(repo_id=repo_id, repo_type=kind, exist_ok=True,
                        private=False, **extra)
        logger.info("ready: %s (%s)", repo_id, kind)


def push_dataset(token: str | None = None, work_dir: Path | None = None) -> None:
    """Pack every split and upload the tarballs plus a dataset card."""
    from huggingface_hub import HfApi

    token = token or _token()
    api = HfApi(token=token)
    work_dir = work_dir or (config.PROCESSED_DIR / "_archives")

    stats_path = config.RESULTS_DIR / "dataset_stats.json"
    stats = json.loads(stats_path.read_text()) if stats_path.exists() else None

    for split in SPLITS:
        archive = pack_split(split, work_dir)
        api.upload_file(
            path_or_fileobj=str(archive),
            path_in_repo=f"{split}.tar.gz",
            repo_id=config.HF_DATASET_REPO,
            repo_type="dataset",
            commit_message=f"add {split} split",
        )
        logger.info("uploaded %s", archive.name)

    api.upload_file(
        path_or_fileobj=dataset_card(stats).encode(),
        path_in_repo="README.md",
        repo_id=config.HF_DATASET_REPO,
        repo_type="dataset",
        commit_message="dataset card",
    )
    logger.info("dataset published: https://huggingface.co/datasets/%s",
                config.HF_DATASET_REPO)


SPACE_CARD = f"""---
title: Candlestick Pattern Detector
emoji: 📈
colorFrom: green
colorTo: red
sdk: gradio
app_file: app.py
pinned: false
license: mit
short_description: YOLO candlestick pattern detector + honest signal test
---

# Candlestick pattern detector

Finds {config.NUM_CLASSES} candlestick patterns in a {config.WINDOW}-candle daily chart
with a fine-tuned YOLO11n, and reports -- honestly -- whether those detections improve
next-day direction prediction over a plain price-feature baseline.

Training labels came from TA-Lib's `CDLxxx` rules, not from human annotation.

Code: https://github.com/{config.HF_USER}/{config.GITHUB_REPO}
"""


def model_card(detection: dict | None, signal: dict | None) -> str:
    """Compose the model card, including the downstream finding.

    The Colab notebook writes a card at training time that can only know the
    detection numbers. Once the signal study has run, the headline result is
    what a visitor most needs to see, so the card is rewritten here with both --
    including the null result, stated up front rather than buried.
    """
    rows = ""
    if detection:
        rows = "\n".join(
            f"| {c} | {v.get('support', 0)} | "
            + " | ".join(
                f"{v[k]:.3f}" if isinstance(v.get(k), (int, float)) else "n/a"
                for k in ("precision", "recall", "mAP50")
            ) + " |"
            for c, v in detection["per_class"].items()
        )
        agg = detection["aggregate"]
        rows += (f"\n| **aggregate** | | **{agg['precision']:.3f}** | "
                 f"**{agg['recall']:.3f}** | **{agg['mAP50']:.3f}** |")

    finding = "_Downstream signal study not yet run._"
    if signal:
        bs = signal["comparison"]["bootstrap"]
        mc = signal["comparison"]["mcnemar"]
        ev = signal["evaluation"]
        b = signal["variants"]["baseline"]
        majority = max(b["base_rate"], 1.0 - b["base_rate"])
        finding = (
            f"Adding this detector's predictions to a plain price-feature baseline "
            f"changed next-day direction accuracy by **{bs['delta_accuracy']:+.4f}** "
            f"(95% bootstrap CI {bs['ci95_low']:+.4f} to {bs['ci95_high']:+.4f}, "
            f"McNemar p = {mc['p_value']:.3f}) over {ev['n_days']} out-of-sample "
            f"days on {ev['ticker']}. The interval contains zero. Neither variant "
            f"beats the majority-class rate of {majority:.4f}, and both have a ROC "
            f"AUC near {b['roc_auc']:.3f}.\n\n"
            f"**So: this model detects the patterns well, and detecting them does "
            f"not help predict the next day.** That is the result, reported as found."
        )

    return f"""---
license: mit
tags: [object-detection, yolo, ultralytics, candlestick, finance]
library_name: ultralytics
pipeline_tag: object-detection
---

# Candlestick pattern detector (YOLO11n)

Detects {config.NUM_CLASSES} candlestick patterns in 640x640 renderings of
{config.WINDOW}-candle daily charts.

## The headline finding

{finding}

## Labels are rule-based, not human-verified

Training boxes came from TA-Lib's `CDLxxx` functions. Nobody annotated these
charts by hand, so this model imitates a published heuristic. Where TA-Lib and
an experienced trader would disagree about the same candles, this model follows
TA-Lib. Detection metrics below therefore measure **agreement with a rule**, not
correctness.

## Detection, held-out test split

| class | instances | precision | recall | mAP@50 |
|---|---:|---:|---:|---:|
{rows}

Reported per class because the classes are very unevenly represented. The
pattern in those numbers is not random: classes defined by a relationship
between whole candle bodies (Engulfing, Harami) are close to solved, while those
defined by a proportion inside a single candle (Hammer, Shooting Star, the
Stars) are much harder -- at this resolution a candle body is only a few pixels
tall, so the measurement the rule depends on is the one the image barely
resolves.

## Usage

```python
from huggingface_hub import hf_hub_download
from ultralytics import YOLO

model = YOLO(hf_hub_download("{config.HF_MODEL_REPO}", "best.pt"))
results = model.predict("chart.png", conf={config.CONF_THRESHOLD})
```

Charts must be rendered the same way the training data was: {config.WINDOW}
candles, {config.IMG_SIZE}x{config.IMG_SIZE}, no axes, no gridlines, no volume
panel. Use `src/data_pipeline/render_charts.py` from the repo -- a differently
drawn chart is an input distribution this model has never seen. Note also that
Ultralytics expects **BGR** arrays while most renderers emit RGB.

## Splits

Chronological with an embargo gap, never random. Consecutive windows overlap in
19 of 20 candles, so the first {config.EMBARGO_BARS} windows after each boundary
are discarded and no test chart shares a candle with a training chart.

- Code: https://github.com/{config.HF_USER}/{config.GITHUB_REPO}
- Dataset: https://huggingface.co/datasets/{config.HF_DATASET_REPO}
- Demo: https://huggingface.co/spaces/{config.HF_SPACE_REPO}

Not investment advice.
"""


def push_model_card(token: str | None = None) -> None:
    """Rewrite the model card from the published results files."""
    from huggingface_hub import HfApi

    token = token or _token()
    api = HfApi(token=token)
    det_p = config.RESULTS_DIR / "detection_metrics.json"
    sig_p = config.RESULTS_DIR / "downstream_signal_comparison.json"
    card = model_card(
        json.loads(det_p.read_text()) if det_p.exists() else None,
        json.loads(sig_p.read_text()) if sig_p.exists() else None,
    )
    api.upload_file(
        path_or_fileobj=card.encode(), path_in_repo="README.md",
        repo_id=config.HF_MODEL_REPO, repo_type="model",
        commit_message="model card with detection and downstream results",
    )
    api.upload_folder(
        folder_path=str(config.RESULTS_DIR), path_in_repo="results",
        repo_id=config.HF_MODEL_REPO, repo_type="model",
        allow_patterns=["*.json"], commit_message="publish results json",
    )
    logger.info("model card updated: https://huggingface.co/%s", config.HF_MODEL_REPO)


def push_space(token: str | None = None) -> None:
    """Deploy the Gradio Space.

    Uploads ``demo/`` at the Space root, then the real ``src/`` package beside
    it and the published ``results/`` JSON. Shipping the actual source modules
    rather than a copy is deliberate: the demo must render charts with the exact
    same ``render_window`` the training data used, and a duplicated copy would
    eventually drift, silently degrading the detector's accuracy in the demo
    for reasons nobody could see.
    """
    from huggingface_hub import HfApi

    token = token or _token()
    api = HfApi(token=token)
    root = config.PROJECT_ROOT

    api.upload_folder(
        folder_path=str(root / "demo"),
        repo_id=config.HF_SPACE_REPO,
        repo_type="space",
        commit_message="deploy demo app",
        ignore_patterns=["__pycache__/*", "*.pyc"],
    )
    api.upload_folder(
        folder_path=str(root / "src"),
        path_in_repo="src",
        repo_id=config.HF_SPACE_REPO,
        repo_type="space",
        commit_message="ship shared source modules",
        ignore_patterns=["__pycache__/*", "*.pyc"],
    )
    if config.RESULTS_DIR.exists():
        api.upload_folder(
            folder_path=str(config.RESULTS_DIR),
            path_in_repo="results",
            repo_id=config.HF_SPACE_REPO,
            repo_type="space",
            commit_message="publish results",
            allow_patterns=["*.json"],
        )
    api.upload_file(
        path_or_fileobj=SPACE_CARD.encode(),
        path_in_repo="README.md",
        repo_id=config.HF_SPACE_REPO,
        repo_type="space",
        commit_message="space card",
    )
    logger.info("space deployed: https://huggingface.co/spaces/%s", config.HF_SPACE_REPO)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("target",
                        choices=["repos", "dataset", "space", "card", "all"])
    args = parser.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    tok = _token()
    if args.target in ("repos", "all"):
        ensure_repos(tok)
    if args.target in ("dataset", "all"):
        push_dataset(tok)
    if args.target in ("card", "all"):
        push_model_card(tok)
    if args.target in ("space", "all"):
        push_space(tok)
